# Generated by Django 4.0.3 on 2023-07-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20230713_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 7, 28, 10, 1, 9, 253654)),
        ),
    ]
