# Generated by Django 4.0.3 on 2023-06-28 15:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 28, 15, 15, 15, 42035))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 28, 15, 15, 15, 42035))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('financial_year', models.IntegerField()),
                ('asset_owner', models.CharField(max_length=150)),
                ('company_code', models.CharField(max_length=150)),
                ('asset_class', models.IntegerField()),
                ('asset_class_descript', models.CharField(max_length=150)),
                ('asset', models.IntegerField()),
                ('sub_no', models.IntegerField()),
                ('asset_description', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('type_name', models.CharField(blank=True, max_length=150, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('personnel_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('sublocation', models.CharField(blank=True, max_length=150, null=True)),
                ('leasing_company_code', models.IntegerField(blank=True, null=True)),
                ('leasing_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('capitalization_date', models.CharField(max_length=25)),
                ('plant', models.IntegerField()),
                ('acquisition_value', models.FloatField()),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('high_value_flag', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
