# Generated by Django 4.0.3 on 2023-07-27 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_asset', '0002_alter_assetdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 7, 27, 12, 6, 36, 237128)),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='acquisition_value',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='asset',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='asset_class',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='book_value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 7, 27, 12, 6, 36, 237128)),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='financial_year',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='leasing_company_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='personnel_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='plant',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='sub_no',
            field=models.CharField(max_length=150),
        ),
    ]
