# Generated by Django 4.0.3 on 2023-07-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_asset', '0003_alter_assetdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdata',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 7, 28, 10, 1, 9, 253654)),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 7, 28, 10, 1, 9, 253654)),
        ),
    ]
