# Generated by Django 4.0.3 on 2023-07-28 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 7, 28, 10, 8, 14, 820953)),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
