# Generated by Django 4.0.3 on 2023-06-24 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 6, 24, 10, 37, 28, 890932)),
        ),
    ]
