# Generated by Django 4.0.3 on 2023-07-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_type', '0002_alter_assettype_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 7, 28, 10, 1, 9, 253654)),
        ),
    ]
